[package]
name = "shronk_ip"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
maxminddb = "0.24.0"
serde = "1.0.198"
tide = "0.16.0"
async-std = { version = "1.6.0", features = ["attributes"] }
